# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1c2c6c6e5e368cf52c51beb64a18e60218392b535c95a13644fea5ba84898e5d6a93ba64ff2eb32dba17955283828c925744b5e2f3e31c14767a6da0661bde0

test:
  secret_key_base: ce5ca82817df82e8041c84b7c36e3e4a7a7e947c4191db3f03735f8a4d2574f0c42468c3adb70d3cfd35e28bfc980fe1761e0232df13ffa093fab970ae393107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
